# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0003_auto_20170524_1501'),
    ]

    operations = [
        migrations.RenameModel('Participant', 'Participation'),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Participation', 'verbose_name_plural': 'Participants'},
        ),
    ]
