# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0004_rename_participant_to_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(blank=True, max_length=32, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '050123123' or '+35850123123'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid postal code.', regex='^\\d{5}$')], verbose_name='Zip/Postal code'),
        ),
        migrations.AlterField(
            model_name='member',
            name='street_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='Street address'),
        ),
    ]
