# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:23
from __future__ import unicode_literals

from django.db import migrations, models


def create_organizations(apps, schema_editor):
    ServiceForm = apps.get_model('serviceform', 'ServiceForm')
    Organization = apps.get_model('serviceform', 'Organization')

    for s in ServiceForm.objects.all():
        Organization.objects.create(name=s.slug)


def null(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0005_auto_20170524_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Organization name')),
            ],
        ),
        migrations.RunPython(create_organizations, null),
    ]
