# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def assign_organizations_to_members(apps, schema_editor):
    Organization = apps.get_model('serviceform', 'Organization')
    Member = apps.get_model('serviceform', 'Member')

    for m in Member.objects.all():
        m.organization = Organization.objects.get(name=m.form.slug)
        m.save()


def null(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0006_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceform.Organization'),
        ),
        migrations.RunPython(assign_organizations_to_members, null),

        migrations.AlterField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='serviceform.Organization'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='form',
        ),
    ]
