# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 08:47
from __future__ import unicode_literals

from django.db import migrations
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0009_remove_participation_contact_detail_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='responsibles',
            field=select2.fields.ManyToManyField(blank=True, related_name='activity_responsibles', sorted=False, to='serviceform.Member', verbose_name='Responsible persons'),
        ),
        migrations.AlterField(
            model_name='activitychoice',
            name='responsibles',
            field=select2.fields.ManyToManyField(blank=True, related_name='activitychoice_responsibles', sorted=False, to='serviceform.Member', verbose_name='Responsible persons'),
        ),
        migrations.AlterField(
            model_name='level1category',
            name='responsibles',
            field=select2.fields.ManyToManyField(blank=True, related_name='level1category_responsibles', sorted=False, to='serviceform.Member', verbose_name='Responsible persons'),
        ),
        migrations.AlterField(
            model_name='level2category',
            name='responsibles',
            field=select2.fields.ManyToManyField(blank=True, related_name='level2category_responsibles', sorted=False, to='serviceform.Member', verbose_name='Responsible persons'),
        ),
        migrations.AlterField(
            model_name='question',
            name='responsibles',
            field=select2.fields.ManyToManyField(blank=True, related_name='question_responsibles', sorted=False, to='serviceform.Member', verbose_name='Responsible persons'),
        ),
    ]
