# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0010_rename_member_related_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='responsibles',
            field=select2.fields.ManyToManyField(blank=True, related_name='serviceform_responsibles', sorted=False, to='serviceform.Member', verbose_name='Responsible persons'),
        ),
    ]
