# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0011_auto_20170526_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='level1category',
            name='skip_numbering',
            field=models.BooleanField(default=False, verbose_name='Skip'),
        ),
        migrations.AddField(
            model_name='level2category',
            name='skip_numbering',
            field=models.BooleanField(default=False, verbose_name='Skip'),
        ),
        migrations.AddField(
            model_name='question',
            name='skip_numbering',
            field=models.BooleanField(default=False, verbose_name='Skip'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='skip_numbering',
            field=models.BooleanField(default=False, verbose_name='Skip'),
        ),
    ]
