# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def organization_to_emailtemplates(apps, schema_editor):
    EmailTemplate = apps.get_model('serviceform', 'EmailTemplate')

    for et in EmailTemplate.objects.all():
        et.organization = et.form.organization
        et.name = f'{et.name} ({et.form.name})'
        et.save()


def null(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0012_auto_20170526_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceform.Organization'),
        ),
        migrations.RunPython(organization_to_emailtemplates, null)
    ]
