# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0013_emailtemplate_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='form',
        ),
    ]
