# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0014_remove_emailtemplate_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email_to_member_auth_link',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to member when auth link is requested', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serviceform.EmailTemplate', verbose_name='Auth link email to member'),
        ),
    ]
