# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0016_auto_20170630_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParticipantLog',
            new_name='ParticipationLog',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='allow_participant_email',
            new_name='allow_participation_email',
        ),
        migrations.RenameField(
            model_name='participationactivity',
            old_name='participant',
            new_name='participation',
        ),
        migrations.RenameField(
            model_name='participationlog',
            old_name='participant',
            new_name='participation',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='participant',
            new_name='participation',
        ),
        migrations.RemoveField(
            model_name='formrevision',
            name='send_bulk_email_to_participants',
        ),
        migrations.RemoveField(
            model_name='serviceform',
            name='email_to_former_participants',
        ),
        migrations.RemoveField(
            model_name='serviceform',
            name='email_to_participant',
        ),
        migrations.RemoveField(
            model_name='serviceform',
            name='email_to_participant_on_update',
        ),
        migrations.RemoveField(
            model_name='serviceform',
            name='resend_email_to_participant',
        ),
        migrations.RemoveField(
            model_name='serviceform',
            name='verification_email_to_participant',
        ),
        migrations.AddField(
            model_name='formrevision',
            name='send_bulk_email_to_participations',
            field=models.BooleanField(default=True, help_text='Send email to participations that filled the form when this revision was active. Email is sent when new current revision is published.', verbose_name='Send bulk email to participations'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='email_to_former_participations',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to former participations when form is published', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serviceform.EmailTemplate', verbose_name='Bulk email to former participations'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='email_to_participation',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to participation after he has fulfilled his participation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serviceform.EmailTemplate', verbose_name='Email to participation, on finish'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='email_to_participation_on_update',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to participation after he has updated his participation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serviceform.EmailTemplate', verbose_name='Email to participation, on update'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='resend_email_to_participation',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to participation if he requests resending email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serviceform.EmailTemplate', verbose_name='Resend email to participation'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='verification_email_to_participation',
            field=models.ForeignKey(blank=True, help_text='Email verification message that is sent to participation when filling form, if email verification is enabled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serviceform.EmailTemplate', verbose_name='Verification email to participation'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(help_text='Following context may (depending on topic) be available for both subject and content: {{responsible}}, {{participation}}, {{last_modified}}, {{form}}, {{url}}, {{contact}}', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Password that is asked from participations', max_length=32, verbose_name='Password'),
        ),
        migrations.AlterUniqueTogether(
            name='participationactivity',
            unique_together=set([('participation', 'activity')]),
        ),
    ]
