# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='-', max_length=256, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
