# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 10:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0002_serviceform_report_view_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceform',
            options={'verbose_name': 'Service form', 'verbose_name_plural': 'Service forms'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='activitychoice',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='level1category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='level2category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='report_view_permissions',
            field=models.ManyToManyField(help_text='Users that are allowed to view reports', related_name='report_viewers', to=settings.AUTH_USER_MODEL, verbose_name='Report viewers'),
        ),
    ]
