# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0004_auto_20160508_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibilityperson',
            name='owner',
        ),
        migrations.AddField(
            model_name='responsibilityperson',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceform.ServiceForm'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='visible_id',
            field=models.CharField(blank=True, db_index=True, help_text='If you wish to use different numbering system in the form, you can enter your custom id here.', max_length=5, verbose_name='Visible id'),
        ),
        migrations.AlterField(
            model_name='activitychoice',
            name='visible_id',
            field=models.CharField(blank=True, db_index=True, help_text='If you wish to use different numbering system in the form, you can enter your custom id here.', max_length=5, verbose_name='Visible id'),
        ),
        migrations.AlterField(
            model_name='level2category',
            name='visible_id',
            field=models.CharField(blank=True, db_index=True, help_text='If you wish to use different numbering system in the form, you can enter your custom id here.', max_length=5, verbose_name='Visible id'),
        ),
        migrations.AlterField(
            model_name='question',
            name='visible_id',
            field=models.CharField(blank=True, db_index=True, help_text='If you wish to use different numbering system in the form, you can enter your custom id here.', max_length=5, verbose_name='Visible id'),
        ),
    ]
