# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0007_auto_20160508_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceform.ResponsibilityPerson', verbose_name='Responsible person'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '050123123' or '+35850123123'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='responsibilityperson',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '050123123' or '+35850123123'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number'),
        ),
    ]
