# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def null(*args, **kwargs):
    pass


def fill_serviceform_organization(apps, schema_editor):
    ServiceForm = apps.get_model('serviceform', 'ServiceForm')
    Organization = apps.get_model('serviceform', 'Organization')

    for s in ServiceForm.objects.all():
        s.organization = Organization.objects.get(name=s.slug)
        s.save()


def fill_participation_member(apps, schema_editor):
    Participation = apps.get_model('serviceform', 'Participation')
    Member = apps.get_model('serviceform', 'Member')

    for p in Participation.objects.all():
        m = Member.objects.filter(email=p.email).first()
        if not m:
            m = Member()
        m.forenames = p.forenames
        m.surname = p.surname
        m.street_address = p.street_address
        m.postal_code = p.postal_code
        m.city = p.city
        m.email = p.email
        m.phone_number = p.phone_number

        m.membership_type = 'external'
        m.organization = p.form_revision.form.organization
        m.send_email_notifications = p.send_email_allowed

        m.email_verified = p.email_verified
        if p.year_of_birth:
            m.year_of_birth = p.year_of_birth

        for a in p.auth_keys_hash_storage:
            m.auth_keys_hash_storage.append(a)

        m.auth_keys_hash_storage.sort(key=lambda x: x[1])

        m.save()

        p.member = m
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0007_member_organization'),
    ]

    operations = [

        migrations.AddField(
            model_name='participation',
            name='member',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='serviceform.Member'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='organization',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='serviceform.Organization'),
        ),
        migrations.AddField(
            model_name='member',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verified'),
        ),
        migrations.AddField(
            model_name='member',
            name='year_of_birth',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Year of birth'),
        ),
        migrations.RunPython(fill_serviceform_organization, null),
        migrations.RunPython(fill_participation_member, null),
        migrations.AlterField(
            model_name='participation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='serviceform.Member'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='serviceform.Organization'),
        ),
    ]
