# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0008_auto_20160510_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='visible_id',
        ),
        migrations.RemoveField(
            model_name='activitychoice',
            name='visible_id',
        ),
        migrations.RemoveField(
            model_name='level1category',
            name='visible_id',
        ),
        migrations.RemoveField(
            model_name='level2category',
            name='visible_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='visible_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='visible_id',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='If you wish to use different numbering system in the form, you can enter your custom id here.', max_digits=5, null=True, verbose_name='Visible id'),
        ),
        migrations.AddField(
            model_name='activitychoice',
            name='visible_id',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='If you wish to use different numbering system in the form, you can enter your custom id here.', max_digits=5, null=True, verbose_name='Visible id'),
        ),
        migrations.AddField(
            model_name='level1category',
            name='visible_id',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='If you wish to use different numbering system in the form, you can enter your custom id here.', max_digits=5, null=True, verbose_name='Visible id'),
        ),
        migrations.AddField(
            model_name='level2category',
            name='visible_id',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='If you wish to use different numbering system in the form, you can enter your custom id here.', max_digits=5, null=True, verbose_name='Visible id'),
        ),
        migrations.AddField(
            model_name='question',
            name='visible_id',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='If you wish to use different numbering system in the form, you can enter your custom id here.', max_digits=5, null=True, verbose_name='Visible id'),
        ),
    ]
