# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0011_auto_20160510_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order_hint', 'pk'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitychoice',
            options={'ordering': ['order_hint', 'pk'], 'verbose_name': 'Activity choice', 'verbose_name_plural': 'Activity choices'},
        ),
        migrations.AlterModelOptions(
            name='level1category',
            options={'ordering': ['order_hint', 'pk'], 'verbose_name': 'Level 1 category', 'verbose_name_plural': 'Level 1 categories'},
        ),
        migrations.AlterModelOptions(
            name='level2category',
            options={'ordering': ['order_hint', 'pk'], 'verbose_name': 'Level 2 category', 'verbose_name_plural': 'Level 2 categories'},
        ),
    ]
