# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0014_auto_20160511_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='revision',
            field=models.IntegerField(default=0),
        ),
    ]
