# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0021_auto_20160511_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formrevision',
            options={'ordering': ('-valid_from',), 'verbose_name': 'Form revision', 'verbose_name_plural': 'Form revisions'},
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceform.FormRevision', verbose_name='Current revision'),
        ),
    ]
