# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0025_auto_20160512_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitychoice',
            options={'verbose_name': 'Activity choice', 'verbose_name_plural': 'Activity choices'},
        ),
        migrations.AlterModelOptions(
            name='level1category',
            options={'verbose_name': 'Level 1 category', 'verbose_name_plural': 'Level 1 categories'},
        ),
        migrations.AlterModelOptions(
            name='level2category',
            options={'verbose_name': 'Level 2 category', 'verbose_name_plural': 'Level 2 categories'},
        ),
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='activitychoice',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='level1category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='level2category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='multiple_choices_allowed',
            field=models.BooleanField(default=True, help_text='Are multiple choices allowed? If multiple choices are allowed, it will result in checkboxes, if not, radiobuttons are used instead.', verbose_name='Multichoices'),
        ),
    ]
