# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0027_auto_20160513_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('order',), 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
