# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0028_auto_20160513_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participationactivity',
            options={'ordering': ('activity__order',)},
        ),
        migrations.AlterModelOptions(
            name='participationactivitychoice',
            options={'ordering': ('activity_choice__order',)},
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ('question__order',)},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='order_hint',
        ),
        migrations.RemoveField(
            model_name='activitychoice',
            name='order_hint',
        ),
        migrations.RemoveField(
            model_name='level1category',
            name='order_hint',
        ),
        migrations.RemoveField(
            model_name='level2category',
            name='order_hint',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order_hint',
        ),
    ]
