# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0030_auto_20160513_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceform',
            name='send_email_to_activity_responsible',
        ),
        migrations.RemoveField(
            model_name='serviceform',
            name='send_email_to_form_responsible',
        ),
        migrations.AddField(
            model_name='responsibilityperson',
            name='send_email_notifications',
            field=models.BooleanField(default=True, help_text='Send email notifications whenever new participation to administered activities is registered', verbose_name='Send email notifications'),
        ),
    ]
