# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 06:48
from __future__ import unicode_literals

from django.db import migrations

full = ['activity',
        'activitychoice',
        'formrevision',
        'level1category',
        'level2category',
        'question',
        'responsibilityperson',
        'serviceform',
        'emailtemplate',
        ]
delete = [
    'participant',
    'participationactivity',
    'participationactivitychoice',
    'questionanswer',
]

custom_permissions = []

def forwards(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    grp, created = Group.objects.get_or_create(name='Serviceform basic rights')

    def add_perm(_model, _action):
        print('Trying to add permission %s to %s' %(_action, _model))
        ct, created = ContentType.objects.get_or_create(app_label='serviceform', model=_model)
        codename = '%s_%s' % (_action, _model)
        try:
            p = Permission.objects.get(codename=codename, content_type=ct)
        except Permission.DoesNotExist:
            p = Permission.objects.create(codename=codename, name=codename.capitalize().replace('_', ' '), content_type=ct)

        grp.permissions.add(p)

    for model in full:
        for action in ['add', 'change', 'delete']:
            add_perm(model, action)

    for model in delete:
        add_perm(model, 'delete')

def backwards(apps_schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0035_auto_20160515_1006'),
        ('auth', '0001_initial'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
