# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0037_formrevision_send_emails_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrevision',
            name='send_email_task_id',
            field=models.IntegerField(null=True),
        ),
    ]
