# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0038_formrevision_send_email_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formrevision',
            name='send_email_task_id',
        ),
        migrations.AlterField(
            model_name='formrevision',
            name='send_emails_after',
            field=models.DateTimeField(default=datetime.datetime(3000, 1, 1, 0, 0), help_text='Sends bulk email at specified time, after which it will send email for each new participation', verbose_name='Email sending starts'),
        ),
    ]
