# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0039_auto_20160520_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrevision',
            name='send_email_task_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
