# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0040_formrevision_send_email_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formrevision',
            name='send_email_task_id',
        ),
        migrations.AddField(
            model_name='serviceform',
            name='send_email_task_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
