# -*- coding: utf-8 -*-
# Generated by Django 1.9.7.dev20160521075240 on 2016-06-22 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0055_auto_20160622_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formrevision',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='formrevision',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(3000, 1, 1, 0, 0), verbose_name='Valid to'),
        ),
    ]
