# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0057_auto_20160622_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formrevision',
            name='send_emails_after',
            field=models.DateTimeField(default=datetime.datetime(2999, 12, 31, 22, 20, tzinfo=utc), help_text='Sends bulk email to responsibility persons at specified time, after which it will send email for each new participation', verbose_name='Email sending starts'),
        ),
        migrations.AlterField(
            model_name='formrevision',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2999, 12, 31, 22, 20, tzinfo=utc), verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='formrevision',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2999, 12, 31, 22, 20, tzinfo=utc), verbose_name='Valid to'),
        ),
    ]
