# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0059_auto_20160726_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='instructions',
            field=models.TextField(blank=True, help_text='Use HTML formatting. Leave this empty to use default', null=True, verbose_name='Instructions'),
        ),
    ]
