# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import serviceform.models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0062_auto_20160729_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Email name')),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
            },
        ),
        migrations.AlterField(
            model_name='level1category',
            name='background_color',
            field=serviceform.models.ColorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='level2category',
            name='background_color',
            field=serviceform.models.ColorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='activity_color',
            field=serviceform.models.ColorField(blank=True, null=True, verbose_name='Activity default background color'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='level1_color',
            field=serviceform.models.ColorField(blank=True, null=True, verbose_name='Level 1 category default background color'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='level2_color',
            field=serviceform.models.ColorField(blank=True, null=True, verbose_name='Level 2 category default background color'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceform.ServiceForm'),
        ),
    ]
