# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0063_auto_20160729_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='email_to_former_participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serviceform.EmailTemplate'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='email_to_participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serviceform.EmailTemplate'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='email_to_responsibles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serviceform.EmailTemplate'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(help_text='Leave empty to use default. Following context may be available for both subject and content: responsible, participant, form', verbose_name='Content'),
        ),
    ]
