# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0065_auto_20160729_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='sent',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
