# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0068_auto_20160729_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='resend_email_to_participant',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to participant if he requests resending email', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serviceform.EmailTemplate'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='email_to_participants',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to participant after he has fulfilled his participation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serviceform.EmailTemplate'),
        ),
    ]
