# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0069_auto_20160729_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceform',
            old_name='email_to_participants',
            new_name='email_to_participant',
        ),
    ]
