# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0072_auto_20160729_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibilityperson',
            options={'ordering': ('surname',), 'verbose_name': 'Responsibility person', 'verbose_name_plural': 'Responsibility persons'},
        ),
        migrations.AddField(
            model_name='serviceform',
            name='email_to_invited_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serviceform.EmailTemplate', verbose_name='Invite email'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(help_text='Following context may be available for both subject and content: responsible, participant, form, contact', verbose_name='Content'),
        ),
    ]
