# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0073_auto_20160812_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(help_text='Following context may be available for both subject and content: responsible, participant, last_modified, form, url, contact', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='email_to_invited_users',
            field=models.ForeignKey(blank=True, help_text='Email that is sent when user is invited to the form manually via invite form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serviceform.EmailTemplate', verbose_name='Invite email'),
        ),
    ]
