# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0074_auto_20160812_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='custom_id',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Custom numbering'),
        ),
        migrations.AddField(
            model_name='activitychoice',
            name='custom_id',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Custom numbering'),
        ),
    ]
