# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0076_auto_20160816_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='year_of_birth',
            field=models.SmallIntegerField(null=True, verbose_name='Year of birth'),
        ),
    ]
