# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0079_auto_20160817_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(),
        ),
    ]
