# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0087_serviceform_email_to_responsible_auth_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='flow_by_categories',
            field=models.BooleanField(default=0, verbose_name='Split participation form to level 1 categories'),
        ),
    ]
