# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import serviceform.models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0089_auto_20160911_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(help_text='Following context may (depending on topic) be available for both subject and content: {{responsible}}, {{participant}}, {{last_modified}}, {{form}}, {{url}}, {{contact}}', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='level1category',
            name='background_color',
            field=serviceform.models.ColorField(blank=True, null=True, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='level2category',
            name='background_color',
            field=serviceform.models.ColorField(blank=True, null=True, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='activity_color',
            field=serviceform.models.ColorField(blank=True, help_text='If left blank (black), it will be derived from level 2 background color', null=True, verbose_name='Activity default background color'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='level1_color',
            field=serviceform.models.ColorField(blank=True, help_text='If left blank (black), default coloring will be used', null=True, verbose_name='Level 1 category default background color'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='level2_color',
            field=serviceform.models.ColorField(blank=True, help_text='If left blank (black), it will be derived from level 1 background color', null=True, verbose_name='Level 2 category default background color'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='login_text',
            field=models.TextField(blank=True, help_text='This will be shown in the login screen', null=True, verbose_name='Login text'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Password that is asked from participants', max_length=32, verbose_name='Password'),
        ),
    ]
