# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 08:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0096_auto_20160918_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='postal_code',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid postal code.', regex='^\\d{5}$')], verbose_name='Zip/Postal code'),
        ),
        migrations.AlterField(
            model_name='responsibilityperson',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid postal code.', regex='^\\d{5}$')], verbose_name='Zip/Postal code'),
        ),
        migrations.AlterUniqueTogether(
            name='formrevision',
            unique_together=set([('form', 'name')]),
        ),
    ]
