# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 10:42
from __future__ import unicode_literals

from django.db import migrations
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0101_auto_20160925_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='responsibles',
            field=select2.fields.ManyToManyField(blank=True, related_name='activity_related', to='serviceform.ResponsibilityPerson', verbose_name='Responsible persons'),
        ),
        migrations.AddField(
            model_name='activitychoice',
            name='responsibles',
            field=select2.fields.ManyToManyField(blank=True, related_name='activitychoice_related', to='serviceform.ResponsibilityPerson', verbose_name='Responsible persons'),
        ),
        migrations.AddField(
            model_name='level1category',
            name='responsibles',
            field=select2.fields.ManyToManyField(blank=True, related_name='level1category_related', to='serviceform.ResponsibilityPerson', verbose_name='Responsible persons'),
        ),
        migrations.AddField(
            model_name='level2category',
            name='responsibles',
            field=select2.fields.ManyToManyField(blank=True, related_name='level2category_related', to='serviceform.ResponsibilityPerson', verbose_name='Responsible persons'),
        ),
        migrations.AddField(
            model_name='question',
            name='responsibles',
            field=select2.fields.ManyToManyField(blank=True, related_name='question_related', to='serviceform.ResponsibilityPerson', verbose_name='Responsible persons'),
        ),
    ]
