# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0104_auto_20160930_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='auth_key_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='responsibilityperson',
            name='auth_key_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
