# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import serviceform.utils


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0106_auto_20161021_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibilityperson',
            name='secret_key',
            field=models.CharField(db_index=True, default=serviceform.utils.generate_uuid, max_length=36, unique=True, verbose_name='Secret key'),
        ),
    ]
