# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 09:41
from __future__ import unicode_literals

from django.db import migrations
fixes = {'{{participant.verification_url}}': '{{url}}',
         '{{participant.personal_url}}': '{{url}}'}


def fix(s):
    for key, value in fixes.items():
        s = s.replace(key, value)
    return s


def fix_messagetemplates(apps, schema_editor):
    EmailTemplate = apps.get_model('serviceform', 'EmailTemplate')
    for et in EmailTemplate.objects.all():
        et.content = fix(et.content)
        et.subject = fix(et.subject)
        et.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0107_auto_20161021_1219'),
    ]

    operations = [
        migrations.RunPython(fix_messagetemplates, reverse)
    ]
