# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0108_fix_messagetemplate_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='context',
            field=models.TextField(default='{}'),
        ),
    ]
