# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 11:37
from __future__ import unicode_literals

from itertools import chain

import django.contrib.postgres.fields.jsonb
from django.db import migrations

def forwards(apps, schema_editor):
    Participant = apps.get_model('serviceform', 'Participant')
    ResponsibilityPerson = apps.get_model('serviceform', 'ResponsibilityPerson')

    for p in chain(Participant.objects.all(), ResponsibilityPerson.objects.all()):
        if p.auth_key_hash:
            p.auth_keys_hash_storage = [(p.auth_key_hash, p.auth_key_expire.timestamp())]
            p.save(update_fields=['auth_keys_hash_storage'])

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0109_emailmessage_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='auth_keys_hash_storage',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='responsibilityperson',
            name='auth_keys_hash_storage',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.RunPython(forwards, backwards)
    ]
