# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 11:17
from __future__ import unicode_literals

from django.db import migrations
import logging

logger = logging.getLogger(__name__)

def forwards(apps, schema_editor):
    ServiceForm = apps.get_model('serviceform', 'ServiceForm')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    UserObjectPermission = apps.get_model('guardian', 'UserObjectPermission')
    ct = ContentType.objects.get(app_label='serviceform', model='serviceform')
    p = Permission.objects.create(codename='can_access_serviceform', content_type=ct, name='Can access Service Form')
    for s in ServiceForm.objects.all():
        if s.owner:
            up, created = UserObjectPermission.objects.get_or_create(user=s.owner, content_type=ct, object_pk=s.pk, permission=p)
            logger.info('Setting permissions for serviceform %s: %s (created: %s)', s.slug, s.owner.username, created)
        for u in s.allowed_users.all():
            up, created = UserObjectPermission.objects.get_or_create(user=u, content_type=ct, object_pk=s.pk, permission=p)
            logger.info('Setting permissions for serviceform %s: %s (created: %s)', s.slug, u.username, created)


def backwards(apps, schema_editor):
    ServiceForm = apps.get_model('serviceform', 'ServiceForm')
    UserObjectPermission = apps.get_model('guardian', 'UserObjectPermission')
    Permission = apps.get_model('auth', 'Permission')
    User = apps.get_model('auth', 'User')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.get(app_label='serviceform', model='serviceform')
    p = Permission.objects.get(codename='can_access_serviceform', content_type=ct)

    for s in ServiceForm.objects.all():
        permissions = UserObjectPermission.objects.filter(content_type=ct, permission=p)
        users = [User.objects.get(pk=p.user_id) for p in permissions]
        s.owner = users[0]
        for u in users[1:]:
            s.allowed_users.add(u)
        s.save()

    p.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0111_auto_20161021_1556'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
