# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160816_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('error', 'Error'), ('done', 'Done'), ('requested', 'Requested'), ('canceled', 'Canceled')], default='requested', max_length=16),
        ),
    ]
