# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20160817_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('error', 'Error'), ('requested', 'Requested'), ('canceled', 'Canceled')], default='requested', max_length=16),
        ),
    ]
