# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0003_auto_20160508_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level1category',
            name='visible_id',
            field=models.CharField(blank=True, db_index=True, help_text='If you wish to use different numbering system in the form, you can enter your custom id here.', max_length=5, verbose_name='Visible id'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='report_view_permissions',
            field=models.ManyToManyField(blank=True, help_text='Users that are allowed to view reports', related_name='report_viewers', to=settings.AUTH_USER_MODEL, verbose_name='Report viewers'),
        ),
    ]
