# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0009_auto_20160510_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='visible_id',
            new_name='order_hint',
        ),
        migrations.RenameField(
            model_name='activitychoice',
            old_name='visible_id',
            new_name='order_hint',
        ),
        migrations.RenameField(
            model_name='level1category',
            old_name='visible_id',
            new_name='order_hint',
        ),
        migrations.RenameField(
            model_name='level2category',
            old_name='visible_id',
            new_name='order_hint',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='visible_id',
            new_name='order_hint',
        ),
    ]
