# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0013_auto_20160510_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='_old_revisions',
            field=models.TextField(blank=True, default='', verbose_name='Old revisions'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='revision',
            field=models.IntegerField(default=0, verbose_name='Form revision, for example year'),
        ),
    ]
