# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0015_participant_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Revision name')),
            ],
            options={
                'verbose_name_plural': 'Form revisions',
                'verbose_name': 'Form revision',
            },
        ),
        migrations.RemoveField(
            model_name='participant',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='serviceform',
            name='_old_revisions',
        ),
        migrations.RemoveField(
            model_name='serviceform',
            name='revision',
        ),
        migrations.AddField(
            model_name='formrevision',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceform.ServiceForm'),
        ),
        migrations.AddField(
            model_name='participant',
            name='form_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceform.FormRevision'),
        ),
        migrations.AddField(
            model_name='participationactivity',
            name='form_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceform.FormRevision'),
        ),
        migrations.AddField(
            model_name='participationactivitychoice',
            name='form_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceform.FormRevision'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='form_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceform.FormRevision'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='current_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceform.FormRevision'),
        ),
    ]
