# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0016_auto_20160511_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceform',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='serviceform',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='formrevision',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Valid from'),
        ),
        migrations.AddField(
            model_name='formrevision',
            name='valid_to',
            field=models.DateField(default=datetime.datetime(3000, 1, 1, 0, 0), verbose_name='Valid to'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceform.FormRevision'),
        ),
    ]
