# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0018_auto_20160511_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formrevision',
            name='name',
            field=models.SlugField(max_length=32, verbose_name='Revision name'),
        ),
    ]
