# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0020_auto_20160511_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formrevision',
            options={'ordering': ('valid_from',), 'verbose_name': 'Form revision', 'verbose_name_plural': 'Form revisions'},
        ),
    ]
