# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import serviceform.models
import serviceform.utils


def forwards(apps, schema_editor):
    ResponsibilityPerson = apps.get_model('serviceform', 'ResponsibilityPerson')
    for i in ResponsibilityPerson.objects.all():
        i.secret_key = serviceform.utils.generate_uuid()
        i.save(update_fields=['secret_key'])


def backwards(schema_editor, apps):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0022_auto_20160512_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibilityperson',
            name='secret_key',
            field=models.CharField(db_index=True, default='', max_length=36),
        ),
        migrations.RunPython(forwards, backwards),
    ]
