# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import serviceform.models
import serviceform.utils


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0024_auto_20160512_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibilityperson',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='responsibilityperson',
            name='secret_key',
            field=models.CharField(db_index=True, default=serviceform.utils.generate_uuid, help_text='Secret key that is used to generate link which can be used to view personal report', max_length=36, unique=True, verbose_name='Secret key'),
        ),
    ]
