# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0026_auto_20160513_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitychoice',
            options={'ordering': ('order',), 'verbose_name': 'Activity choice', 'verbose_name_plural': 'Activity choices'},
        ),
        migrations.AlterModelOptions(
            name='level1category',
            options={'ordering': ('order',), 'verbose_name': 'Level 1 category', 'verbose_name_plural': 'Level 1 categories'},
        ),
        migrations.AlterModelOptions(
            name='level2category',
            options={'ordering': ('order',), 'verbose_name': 'Level 2 category', 'verbose_name_plural': 'Level 2 categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
