# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0029_auto_20160513_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='multiple_choices_allowed',
            field=models.BooleanField(default=True, verbose_name='Multiple choices allowed'),
        ),
    ]
