# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0031_auto_20160513_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibilityperson',
            name='send_email_notifications',
            field=models.BooleanField(default=True, help_text='Send email notifications whenever new participation to administered activities is registered.Email contains also has a link that allows accessing raport of administered activities.', verbose_name='Send email notifications'),
        ),
    ]
