# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0032_auto_20160513_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
