# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0033_auto_20160513_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last updated'),
        ),
    ]
