# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0036_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrevision',
            name='send_emails_after',
            field=models.DateTimeField(default=datetime.datetime(3000, 1, 1, 0, 0), verbose_name='Sends bulk email at specified time, after which it will send email for each new participation'),
        ),
    ]
