# -*- coding: utf-8 -*-
# Generated by Django 1.9.7.dev20160521075240 on 2016-06-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0043_participantlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participationactivity',
            options={'ordering': ('activity__category__category__order', 'activity__category__order', 'activity__order')},
        ),
        migrations.AddField(
            model_name='activity',
            name='people_needed',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount of people needed'),
        ),
        migrations.AddField(
            model_name='activitychoice',
            name='people_needed',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount of people needed'),
        ),
    ]
