# -*- coding: utf-8 -*-
# Generated by Django 1.9.7.dev20160521075240 on 2016-06-20 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import serviceform.models
import serviceform.utils


def forwards(apps, schema_editor):
    Participant = apps.get_model('serviceform', 'Participant')
    for i in Participant.objects.all():
        i.secret_key = serviceform.utils.generate_uuid()
        i.save()

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0044_auto_20160620_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='secret_key',
            field=models.CharField(db_index=True, default=serviceform.utils.generate_uuid, max_length=36, verbose_name='Secret key'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
