# -*- coding: utf-8 -*-
# Generated by Django 1.9.7.dev20160521075240 on 2016-06-20 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceform', '0046_auto_20160620_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_serviceform', to=settings.AUTH_USER_MODEL, verbose_name='Last edited by'),
        ),
    ]
