# -*- coding: utf-8 -*-
# Generated by Django 1.9.7.dev20160521075240 on 2016-06-20 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0048_auto_20160620_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationactivity',
            name='hint_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='participationactivitychoice',
            name='hint_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
