# -*- coding: utf-8 -*-
# Generated by Django 1.9.7.dev20160521075240 on 2016-06-22 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0051_auto_20160622_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='last_finished_form',
            new_name='last_finished_view',
        ),
    ]
