# -*- coding: utf-8 -*-
# Generated by Django 1.9.7.dev20160521075240 on 2016-06-22 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0053_auto_20160622_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceform',
            name='send_emails_after',
        ),
        migrations.AddField(
            model_name='formrevision',
            name='send_emails_after',
            field=models.DateTimeField(default=datetime.datetime(3000, 1, 1, 0, 0), help_text='Sends bulk email to responsibility persons at specified time, after which it will send email for each new participation', verbose_name='Email sending starts'),
        ),
        migrations.AlterField(
            model_name='formrevision',
            name='send_bulk_email_to_participants',
            field=models.BooleanField(default=True, help_text='Send email to participants that filled the form when this revision was active. Email is sent when new current revision is published.', verbose_name='Send bulk email to participants'),
        ),
    ]
