# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0060_serviceform_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibilityperson',
            name='hide_contact_details',
            field=models.BooleanField(default=False, verbose_name='Hide contact details in form'),
        ),
    ]
