# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 08:01
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0061_responsibilityperson_hide_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='level1category',
            name='background_color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level2category',
            name='background_color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='activity_color',
            field=colorful.fields.RGBColorField(blank=True, null=True, verbose_name='Activity default background color'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='level1_color',
            field=colorful.fields.RGBColorField(blank=True, null=True, verbose_name='Level 1 category default background color'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='level2_color',
            field=colorful.fields.RGBColorField(blank=True, null=True, verbose_name='Level 1 category default background color'),
        ),
    ]
