# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0067_auto_20160729_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='bulk_email_to_responsibles',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to responsibles when emailing starts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serviceform.EmailTemplate'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='email_to_former_participants',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to former participants when form is published', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serviceform.EmailTemplate'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='email_to_participants',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to responsibles after he has fulfilled his participation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serviceform.EmailTemplate'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='email_to_responsibles',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to responsibles when new participation is registered', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serviceform.EmailTemplate'),
        ),
    ]
