# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0075_auto_20160813_1436'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduledtasks',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='scheduledtasks',
            name='form',
        ),
        migrations.DeleteModel(
            name='ScheduledTasks',
        ),
    ]
