# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0077_participant_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='year_of_birth',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Year of birth'),
        ),
    ]
