# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-20 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0080_auto_20160818_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunSQL("UPDATE serviceform_questionanswer SET created_at='2016-01-01 12:00:00+02';",''),
    ]
