# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-20 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0083_auto_20160820_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='email_to_participant_on_update',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to participant after he has updated his participation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serviceform.EmailTemplate', verbose_name='Email to participant, on update'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='email_to_participant',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to participant after he has fulfilled his participation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serviceform.EmailTemplate', verbose_name='Email to participant, on finish'),
        )
    ]
