# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0084_auto_20160820_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='forenames',
            field=models.CharField(max_length=64, verbose_name='Forename(s)'),
        ),
        migrations.AlterField(
            model_name='responsibilityperson',
            name='forenames',
            field=models.CharField(max_length=64, verbose_name='Forename(s)'),
        ),
    ]
