# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0085_auto_20160902_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='login_text',
            field=models.TextField(blank=True, null=True, verbose_name='Login text'),
        ),
    ]
