# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0086_serviceform_login_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='email_to_responsible_auth_link',
            field=models.ForeignKey(blank=True, help_text='Email that is sent to responsible when he requests auth link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serviceform.EmailTemplate', verbose_name='Responsible requests auth link'),
        ),
    ]
