# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0088_serviceform_flow_by_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceform',
            name='description',
            field=models.TextField(blank=True, help_text='Description box will be shown before instruction box in participation view.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='instructions',
            field=models.TextField(blank=True, help_text='Use HTML formatting. Leave this empty to use default. This is shown in participation view.', null=True, verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name of the serviceform'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='slug',
            field=models.SlugField(help_text='Tämä on osa lomakkeen osoitetta, ts. lomakkeen osoitteeksi tulee http://localhost:8000/valitsemasi-nimi-urlissa', unique=True, verbose_name='Slug'),
        ),
    ]
