# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0090_auto_20160911_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='allow_skipping_categories',
            field=models.BooleanField(default=False, help_text='In effect only if flow by categories option is enabled. If this option is enabled, user can jump between categories. If disabled, he must proceed them one by one.', verbose_name='Allow jumping between categories'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='flow_by_categories',
            field=models.BooleanField(default=False, help_text='Please note that preview shows full form despite this option', verbose_name='Split participation form to level 1 categories'),
        ),
    ]
