# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 07:20
from __future__ import unicode_literals

from itertools import chain

from django.db import migrations, models


def forwards(apps, schema_editor):
    Activity = apps.get_model('serviceform', 'Activity')
    ActivityChoice = apps.get_model('serviceform', 'ActivityChoice')
    for a in chain(*[i.objects.filter(custom_id__isnull=False).exclude(custom_id='') for i in [Activity, ActivityChoice]]):
        print('setting skip numbering to true to', a, a.name)
        a.skip_numbering = True
        a.save()

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0092_responsibilityperson_show_full_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='skip_numbering',
            field=models.BooleanField(default=False, verbose_name='Skip numbering'),
        ),
        migrations.AddField(
            model_name='activitychoice',
            name='skip_numbering',
            field=models.BooleanField(default=False, verbose_name='Skip numbering'),
        ),
        migrations.RunPython(forwards, backwards)
    ]
