# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0093_auto_20160918_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='activitychoice',
            name='custom_id',
        ),
    ]
