# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0094_auto_20160918_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='skip_numbering',
            field=models.BooleanField(default=False, verbose_name='Skip count'),
        ),
        migrations.AlterField(
            model_name='activitychoice',
            name='skip_numbering',
            field=models.BooleanField(default=False, verbose_name='Skip count'),
        ),
    ]
