# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0097_auto_20160918_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='require_email_verification',
            field=models.BooleanField(default=False, verbose_name='Require email verification'),
        ),
        migrations.AlterField(
            model_name='formrevision',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceform.ServiceForm', verbose_name='Service form'),
        ),
    ]
