# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0100_participant_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceform',
            name='require_email_verification',
            field=models.BooleanField(default=True, verbose_name='Require email verification'),
        ),
    ]
