# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:02
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    for model_name in ['Activity', 'ActivityChoice', 'Level1Category', 'Level2Category', 'Question']:
        model = apps.get_model('serviceform', model_name)
        for m in model.objects.all():
            if m.responsible and m.responsible not in m.responsibles.all():
                m.responsibles.add(m.responsible)
                m.save()


def backwards(apps, schema_editor):
    for model_name in ['Activity', 'ActivityChoice', 'Level1Category', 'Level2Category', 'Question']:
        model = apps.get_model('serviceform', model_name)
        for m in model.objects.all():
            if m.responsibles.first():
                m.responsible = m.responsibles.first()
                m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0102_auto_20160930_1342'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
