# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0103_migrate_responsibles_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='activitychoice',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='level1category',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='level2category',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='question',
            name='responsible',
        ),
        migrations.AlterField(
            model_name='activity',
            name='multiple_choices_allowed',
            field=models.BooleanField(default=True, verbose_name='Multichoice'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='people_needed',
            field=models.PositiveIntegerField(default=0, verbose_name='Needed'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='skip_numbering',
            field=models.BooleanField(default=False, verbose_name='Skip'),
        ),
        migrations.AlterField(
            model_name='activitychoice',
            name='people_needed',
            field=models.PositiveIntegerField(default=0, verbose_name='Needed'),
        ),
        migrations.AlterField(
            model_name='activitychoice',
            name='skip_numbering',
            field=models.BooleanField(default=False, verbose_name='Skip'),
        ),
    ]
