# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0110_auto_20161021_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='auth_key_expire',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='auth_key_hash',
        ),
        migrations.RemoveField(
            model_name='responsibilityperson',
            name='auth_key_expire',
        ),
        migrations.RemoveField(
            model_name='responsibilityperson',
            name='auth_key_hash',
        ),
    ]
