# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceform', '0112_guardian_permissions_for_serviceform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceform',
            name='allowed_users',
        ),
        migrations.RemoveField(
            model_name='serviceform',
            name='owner',
        ),
    ]
